---

- name: reload the device
  cli_command:
    command: reload location all
    prompt:
      - '\[confirm\]'
      - '\[confirm\]'
    answer:
     - y
     - y
    check_all: true
  ignore_errors: true
  vars:
    ansible_command_timeout: 5

- name: wait for device up
  include_tasks: wait_for.yml
