---

- name: copy run sta
  cli_command:
    command: copy run sta

# 10秒後に再起動がかかるようにする
# コマンドプロンプトが戻ってこないことがあるためignore_errorsする
- name: reload the device
  cli_command:
    command: reload in 10
  ignore_errors: true
  vars:
    ansible_command_timeout: 5

- name: wait for device up
  include_tasks: wait_for.yml
