---

- name: Retrieve IOS-XR version
  # hosts: routers
  hosts: r1
  gather_facts: False

  tasks:
    - name: show version
      cisco.iosxr.iosxr_command:
        commands:
          - show version
      when:
        - ansible_network_os == 'cisco.iosxr.iosxr'
