---

-
  block:

    - name: show ip route vrf all
      cli_command:
        command: show ip route vrf all
      register: cli_result

    - debug: msg="{{ cli_result.stdout }}"

    - name: Save command output
      local_action:
        module: copy
        content: "{{ cli_result.stdout }}"
        dest: "{{ LOG_DIR }}/{{ filename }}"
      vars:
        date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
        filename: "{{ inventory_hostname }}_{{ role_name|basename }}_{{ date }}.txt"

    - name: run script
      command: "{{ SCRIPT }} -d {{ LOG_DIR }} -p {{ inventory_hostname }} -t {{ TEXTFSM }}"
      #args:
      #  chdir: "{{ role_path }}/files"
      delegate_to: localhost
      register: script_result

    - debug: msg="{{ script_result.stdout }}"
