---

- name: ansible version check
  include_tasks: ansible_version_check.yml

- name: pip module check
  # 変数を読み込んでループを回すため、動的に読み込むinclude_tasksでなければならない(import_tasksは動作しない)
  include_tasks: pip_module_check.yml
  loop: "{{ pip_module_list }}"
