---

#
# pythonモジュールがインストールされているかチェック
#

- shell: pip show "{{ item }}" | grep ^Version | cut -d ' ' -f 2
  changed_when: false
  register: pip_module_check

- assert:
    that:
      - pip_module_check.stdout
    fail_msg: "{{ item }} is required but not found, please run: pip install ' + {{ item }}"
    success_msg: "OK: {{ item }} is installed"