---

# 実行時間を記録する
- name: get current time
  local_action:
    module: set_fact
    _date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

-
  block:
    - name: show bgp neighbors
      cisco.iosxr.iosxr_command:
        commands:
          - show bgp neighbors
      register: r
      when:
        - ansible_network_os in ['iosxr', 'cisco.iosxr.iosxr']

    # - debug: var=r

    #
    # レポート用に実行結果をset_factする
    #
    - local_action:
        module: set_fact
        _result: "{{ 'NG' if r.skipped|d(false) or r.failed|d(false) else 'OK' }}"
        _stdout: "{{ r.stdout[0]|d('') }}"

  rescue:
    # - debug:
    #     var: r

    #
    # レポート用に失敗した情報をset_factする
    #
    - local_action:
        module: set_fact
        _result: 'NG'
