---

# サマリ情報の生成は一度だけでよい
-
  block:
    - name: summary
      debug:
        msg: "{{ lookup('template', SUMMARY_TEXT) }}"
      changed_when: false
      ignore_errors: true

  # run_once: true でもよい
  when:
    - inventory_hostname == ansible_play_hosts_all[0]
    - _result is defined
