---

# ログは全ノード同じ場所に置く
- name: Create log directory if not exists
  local_action:
    module: file
    path: "{{ LOG_DIR }}"
    state: directory
    recurse: true
  changed_when: false
  run_once: true

-
  block: # ipingコマンドを実行してファイルに保存するブロック

    - name: iping
      cli_command:
        command: "iping -V {{ VRF }} -i 0 {{ item }}"
      loop: "{{ TARGETS }}"
      register: r

    - set_fact:
        cli_output: |-
          {# TARGETS配列とr.results配列を結合したのちループを回す #}
          {% for item in (TARGETS | zip(r.results) | list) -%}
          ============================================================
          {{ date }}
          iping -v {{ VRF }} {{ item[0] }}
          ============================================================

          {{ item[1].stdout }}

          {% endfor -%}

    # - debug: msg="{{ cli_output }}"

    - name: Append command output
      local_action:
        module: blockinfile
        block: "{{ cli_output }}"
        path: "{{ LOG_DIR }}/{{ filename }}"
        create: true
        # insertbefore: BOF  # ファイルの先頭に追記
        insertafter: EOF  # ファイルの末尾に追記
        marker: ""
        marker_begin: ""
        marker_end: ""

    # textfsmでパースした結果をset_factしておく
    - set_fact:
        ping_results: "{{ r.results | parse_ping }}"

  vars:
    date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
    filename: "{{ inventory_hostname }}_{{ role_name | basename }}.txt"

  tags:
    - iping