---

- name: set command
  local_action:
    module: set_fact
    CMD: 'clear counters interface '

- name: Gather facts of nxos
  nxos_facts:
    gather_subset: interfaces

# - debug: var=ansible_facts