---

-
  block:

    - name: Gather facts
      include_tasks: "{{ item }}"
      with_first_found:
        - files: "{{ task_file }}"
          paths:
            - "{{ role_path }}/tasks"
          skip: true
      register: r

    - set_fact:
        skipped: "{{ r.skipped|d(false) }}"

    - name: create summary info
      include_tasks: summary.yml

  vars:
    task_file: >-
      {%- if   ansible_network_os is in ['ios', 'cisco.ios.ios'] -%}ios.yml
      {%- elif ansible_network_os is in ['nxos', 'cisco.nxos.nxos'] -%}nxos.yml
      {%- elif ansible_network_os is in ['iosxr', 'cisco.iosxr.iosxr'] -%}iosxr.yml
      {%- else -%}FILE_NOT_FOUND
      {%- endif -%}

  when:
    - inventory_hostname not in EXCLUDE_HOSTS
