---

- name: debug test script
  command: "{{ role_path }}/files/show_ip_route.py"
  args:
    chdir: "{{ role_path }}/files"
  delegate_to: localhost
  run_once: true
  register: r

- debug: msg="{{ r.stdout }}"