---

- name: show ip route
  cli_command:
    command: show ip route
  register: cli_result

- set_fact:
    stdout: "{{ cli_result.stdout }}"
    textfsm: "{{ role_path }}/files/cisco_ios_show_ip_route.textfsm"


# - debug: msg="{{ cli_result.stdout }}"
