---

#
# debug python script
#
# - include_tasks: _debug_python_script.yml
# - meta: end_play


#
# ログディレクトリはホストごとに違うかもしれないのでrun_onceはfalseにしておく
#
- name: Create log directory if not exists
  local_action:
    module: file
    path: "{{ LOG_DIR }}"
    state: directory
    recurse: true
  changed_when: false
  run_once: false


#
# 機種によってルーティングテーブルを表示するコマンドは違うので分岐する
#
-
  block:

    - name: Gather routing table
      include_tasks: "{{ item }}"
      with_first_found:
        - files: "{{ task_file }}"
          paths:
            - "{{ role_path }}/tasks"
          skip: true
      register: r

    - set_fact:
        skipped: "{{ r.skipped|d(false) }}"

    - name: Save command output
      local_action:
        module: copy
        content: "{{ stdout }}"
        dest: "{{ LOG_DIR }}/{{ filename }}"
      vars:
        date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
        filename: "{{ inventory_hostname }}_{{ role_name|basename }}_{{ date }}.txt"


    # - name: Find log files
    #   local_action:
    #     module: find
    #     paths: "{{ LOG_DIR }}"
    #     patterns: "{{ inventory_hostname }}_{{ role_name|basename }}_*.txt"
    #   register: find_result
    #
    # - set_fact:
    #     log_files: "{{ find_result.files | sort(attribute='ctime', reverse=True) | map(attribute='path') | list }}"
    #
    # - debug: var=log_files
    #
    # - debug: msg="{{ log_files[0] }}-{{ log_files[item] }}"

    - name: run script
      command: "{{ role_path }}/files/show_ip_route.py -d {{ LOG_DIR }} -p {{ inventory_hostname }} -t {{ textfsm }}"
      #args:
      #  chdir: "{{ role_path }}/files"
      delegate_to: localhost
      register: script_result

    - debug: msg="{{ script_result.stdout }}"

  vars:
    task_file: >-
      {%- if   ansible_network_os is in ['ios', 'cisco.ios.ios'] -%}ios.yml
      {%- elif ansible_network_os is in ['nxos', 'cisco.nxos.nxos'] -%}nxos.yml
      {%- elif ansible_network_os is in ['iosxr', 'cisco.iosxr.iosxr'] -%}iosxr.yml
      {%- else -%}not_found.yml
      {%- endif -%}

  when:
    - inventory_hostname not in EXCLUDE_HOSTS
