---

# 結果をファイルとして保存するなら、保存先のディレクトリを作成する
- name: create log directory if not exists
  local_action:
    module: file
    path: "{{ LOG_DIR }}"
    state: directory
    recurse: true
  changed_when: false
  run_once: true
  when:
    - SAVE_RESULT is defined and SAVE_RESULT == true

-
  block:

  - name: show bgp neighbors
    include_tasks: show_bgp_neighbors.yml

  - name: parse command output
    include_tasks: parse.yml

  - name: summary
    include_tasks: summary.yml

  when:
    - inventory_hostname not in EXCLUDE_HOSTS
