---

# 実行時間を記録する
- name: get current time
  set_fact:
    _date: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

-
  block:
    - name: show bgp neighbors
      cisco.iosxr.iosxr_command:
        commands:
          - show bgp neighbors
      register: r
      when:
        - ansible_network_os == 'cisco.iosxr.iosxr'

    # - debug:
    #     msg: "{{ r.stdout[0] }}"

    #
    # レポート用に実行結果をset_factする
    #
    - set_fact:
        _result: "{{ 'NG' if r.failed else 'OK' }}"
        _stdout: "{{ r.stdout[0] }}"

  rescue:
    # - debug:
    #     var: r

    #
    # レポート用に失敗した情報をset_factする
    #
    - set_fact:
        _result: 'NG'
